// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: api/spellingbee/v1/spellingbee.proto

package spellingbeepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLettersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLettersRequest) Reset() {
	*x = GetLettersRequest{}
	mi := &file_api_spellingbee_v1_spellingbee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLettersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLettersRequest) ProtoMessage() {}

func (x *GetLettersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_spellingbee_v1_spellingbee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLettersRequest.ProtoReflect.Descriptor instead.
func (*GetLettersRequest) Descriptor() ([]byte, []int) {
	return file_api_spellingbee_v1_spellingbee_proto_rawDescGZIP(), []int{0}
}

type GetLettersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Letters       []string               `protobuf:"bytes,1,rep,name=letters,proto3" json:"letters,omitempty"`
	CenterLetter  string                 `protobuf:"bytes,2,opt,name=center_letter,json=centerLetter,proto3" json:"center_letter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLettersResponse) Reset() {
	*x = GetLettersResponse{}
	mi := &file_api_spellingbee_v1_spellingbee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLettersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLettersResponse) ProtoMessage() {}

func (x *GetLettersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_spellingbee_v1_spellingbee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLettersResponse.ProtoReflect.Descriptor instead.
func (*GetLettersResponse) Descriptor() ([]byte, []int) {
	return file_api_spellingbee_v1_spellingbee_proto_rawDescGZIP(), []int{1}
}

func (x *GetLettersResponse) GetLetters() []string {
	if x != nil {
		return x.Letters
	}
	return nil
}

func (x *GetLettersResponse) GetCenterLetter() string {
	if x != nil {
		return x.CenterLetter
	}
	return ""
}

type SubmitWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWordRequest) Reset() {
	*x = SubmitWordRequest{}
	mi := &file_api_spellingbee_v1_spellingbee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWordRequest) ProtoMessage() {}

func (x *SubmitWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_spellingbee_v1_spellingbee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWordRequest.ProtoReflect.Descriptor instead.
func (*SubmitWordRequest) Descriptor() ([]byte, []int) {
	return file_api_spellingbee_v1_spellingbee_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type SubmitWordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	TotalScore    int32                  `protobuf:"varint,4,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWordResponse) Reset() {
	*x = SubmitWordResponse{}
	mi := &file_api_spellingbee_v1_spellingbee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWordResponse) ProtoMessage() {}

func (x *SubmitWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_spellingbee_v1_spellingbee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWordResponse.ProtoReflect.Descriptor instead.
func (*SubmitWordResponse) Descriptor() ([]byte, []int) {
	return file_api_spellingbee_v1_spellingbee_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitWordResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *SubmitWordResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SubmitWordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitWordResponse) GetTotalScore() int32 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

var File_api_spellingbee_v1_spellingbee_proto protoreflect.FileDescriptor

const file_api_spellingbee_v1_spellingbee_proto_rawDesc = "" +
	"\n" +
	"$api/spellingbee/v1/spellingbee.proto\x12\x0espellingbee.v1\"\x13\n" +
	"\x11GetLettersRequest\"S\n" +
	"\x12GetLettersResponse\x12\x18\n" +
	"\aletters\x18\x01 \x03(\tR\aletters\x12#\n" +
	"\rcenter_letter\x18\x02 \x01(\tR\fcenterLetter\"'\n" +
	"\x11SubmitWordRequest\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\"{\n" +
	"\x12SubmitWordResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vtotal_score\x18\x04 \x01(\x05R\n" +
	"totalScore2\xbe\x01\n" +
	"\x12SpellingBeeService\x12S\n" +
	"\n" +
	"GetLetters\x12!.spellingbee.v1.GetLettersRequest\x1a\".spellingbee.v1.GetLettersResponse\x12S\n" +
	"\n" +
	"SubmitWord\x12!.spellingbee.v1.SubmitWordRequest\x1a\".spellingbee.v1.SubmitWordResponseB3Z1spellingbee_game/api/spellingbee/v1;spellingbeepbb\x06proto3"

var (
	file_api_spellingbee_v1_spellingbee_proto_rawDescOnce sync.Once
	file_api_spellingbee_v1_spellingbee_proto_rawDescData []byte
)

func file_api_spellingbee_v1_spellingbee_proto_rawDescGZIP() []byte {
	file_api_spellingbee_v1_spellingbee_proto_rawDescOnce.Do(func() {
		file_api_spellingbee_v1_spellingbee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_spellingbee_v1_spellingbee_proto_rawDesc), len(file_api_spellingbee_v1_spellingbee_proto_rawDesc)))
	})
	return file_api_spellingbee_v1_spellingbee_proto_rawDescData
}

var file_api_spellingbee_v1_spellingbee_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_spellingbee_v1_spellingbee_proto_goTypes = []any{
	(*GetLettersRequest)(nil),  // 0: spellingbee.v1.GetLettersRequest
	(*GetLettersResponse)(nil), // 1: spellingbee.v1.GetLettersResponse
	(*SubmitWordRequest)(nil),  // 2: spellingbee.v1.SubmitWordRequest
	(*SubmitWordResponse)(nil), // 3: spellingbee.v1.SubmitWordResponse
}
var file_api_spellingbee_v1_spellingbee_proto_depIdxs = []int32{
	0, // 0: spellingbee.v1.SpellingBeeService.GetLetters:input_type -> spellingbee.v1.GetLettersRequest
	2, // 1: spellingbee.v1.SpellingBeeService.SubmitWord:input_type -> spellingbee.v1.SubmitWordRequest
	1, // 2: spellingbee.v1.SpellingBeeService.GetLetters:output_type -> spellingbee.v1.GetLettersResponse
	3, // 3: spellingbee.v1.SpellingBeeService.SubmitWord:output_type -> spellingbee.v1.SubmitWordResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_spellingbee_v1_spellingbee_proto_init() }
func file_api_spellingbee_v1_spellingbee_proto_init() {
	if File_api_spellingbee_v1_spellingbee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_spellingbee_v1_spellingbee_proto_rawDesc), len(file_api_spellingbee_v1_spellingbee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_spellingbee_v1_spellingbee_proto_goTypes,
		DependencyIndexes: file_api_spellingbee_v1_spellingbee_proto_depIdxs,
		MessageInfos:      file_api_spellingbee_v1_spellingbee_proto_msgTypes,
	}.Build()
	File_api_spellingbee_v1_spellingbee_proto = out.File
	file_api_spellingbee_v1_spellingbee_proto_goTypes = nil
	file_api_spellingbee_v1_spellingbee_proto_depIdxs = nil
}
