// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: api/spellingbee/v1/spellingbee.proto

package spellingbeepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpellingBeeService_GetLetters_FullMethodName = "/spellingbee.v1.SpellingBeeService/GetLetters"
	SpellingBeeService_SubmitWord_FullMethodName = "/spellingbee.v1.SpellingBeeService/SubmitWord"
)

// SpellingBeeServiceClient is the client API for SpellingBeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpellingBeeServiceClient interface {
	GetLetters(ctx context.Context, in *GetLettersRequest, opts ...grpc.CallOption) (*GetLettersResponse, error)
	SubmitWord(ctx context.Context, in *SubmitWordRequest, opts ...grpc.CallOption) (*SubmitWordResponse, error)
}

type spellingBeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpellingBeeServiceClient(cc grpc.ClientConnInterface) SpellingBeeServiceClient {
	return &spellingBeeServiceClient{cc}
}

func (c *spellingBeeServiceClient) GetLetters(ctx context.Context, in *GetLettersRequest, opts ...grpc.CallOption) (*GetLettersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLettersResponse)
	err := c.cc.Invoke(ctx, SpellingBeeService_GetLetters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spellingBeeServiceClient) SubmitWord(ctx context.Context, in *SubmitWordRequest, opts ...grpc.CallOption) (*SubmitWordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitWordResponse)
	err := c.cc.Invoke(ctx, SpellingBeeService_SubmitWord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpellingBeeServiceServer is the server API for SpellingBeeService service.
// All implementations must embed UnimplementedSpellingBeeServiceServer
// for forward compatibility.
type SpellingBeeServiceServer interface {
	GetLetters(context.Context, *GetLettersRequest) (*GetLettersResponse, error)
	SubmitWord(context.Context, *SubmitWordRequest) (*SubmitWordResponse, error)
	mustEmbedUnimplementedSpellingBeeServiceServer()
}

// UnimplementedSpellingBeeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpellingBeeServiceServer struct{}

func (UnimplementedSpellingBeeServiceServer) GetLetters(context.Context, *GetLettersRequest) (*GetLettersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLetters not implemented")
}
func (UnimplementedSpellingBeeServiceServer) SubmitWord(context.Context, *SubmitWordRequest) (*SubmitWordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitWord not implemented")
}
func (UnimplementedSpellingBeeServiceServer) mustEmbedUnimplementedSpellingBeeServiceServer() {}
func (UnimplementedSpellingBeeServiceServer) testEmbeddedByValue()                            {}

// UnsafeSpellingBeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpellingBeeServiceServer will
// result in compilation errors.
type UnsafeSpellingBeeServiceServer interface {
	mustEmbedUnimplementedSpellingBeeServiceServer()
}

func RegisterSpellingBeeServiceServer(s grpc.ServiceRegistrar, srv SpellingBeeServiceServer) {
	// If the following call pancis, it indicates UnimplementedSpellingBeeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpellingBeeService_ServiceDesc, srv)
}

func _SpellingBeeService_GetLetters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLettersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpellingBeeServiceServer).GetLetters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpellingBeeService_GetLetters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpellingBeeServiceServer).GetLetters(ctx, req.(*GetLettersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpellingBeeService_SubmitWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpellingBeeServiceServer).SubmitWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpellingBeeService_SubmitWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpellingBeeServiceServer).SubmitWord(ctx, req.(*SubmitWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpellingBeeService_ServiceDesc is the grpc.ServiceDesc for SpellingBeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpellingBeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spellingbee.v1.SpellingBeeService",
	HandlerType: (*SpellingBeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLetters",
			Handler:    _SpellingBeeService_GetLetters_Handler,
		},
		{
			MethodName: "SubmitWord",
			Handler:    _SpellingBeeService_SubmitWord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/spellingbee/v1/spellingbee.proto",
}
